import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Invoice } from "@/types/invoice";
import { toast } from "sonner";

export function useInvoices() {
  return useQuery({
    queryKey: ["invoices"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("invoices")
        .select(`
          *,
          client:clients(id, company_name),
          request:requests(id, request_number),
          estimate:estimates(id, name)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;

      return data.map((row): Invoice => ({
        id: row.id,
        invoiceNumber: row.invoice_number,
        invoiceDate: row.invoice_date,
        clientId: row.client_id || undefined,
        clientName: row.client?.company_name || undefined,
        requestId: row.request_id || undefined,
        requestName: row.request?.request_number || undefined,
        estimateId: row.estimate_id || undefined,
        estimateName: row.estimate?.name || undefined,
        amount: Number(row.amount) || 0,
        status: row.status,
      }));
    },
  });
}

export function useCreateInvoice() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (invoice: Partial<Invoice>) => {
      const { data, error } = await supabase
        .from("invoices")
        .insert({
          invoice_number: "", // Will be auto-generated by trigger
          invoice_date: invoice.invoiceDate || new Date().toISOString().split('T')[0],
          client_id: invoice.clientId || null,
          request_id: invoice.requestId || null,
          estimate_id: invoice.estimateId || null,
          amount: invoice.amount || 0,
          status: invoice.status || "подготовлен",
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoices"] });
      toast.success("Счёт создан");
    },
    onError: () => toast.error("Ошибка при создании счёта"),
  });
}

export function useUpdateInvoice() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...invoice }: Partial<Invoice> & { id: string }) => {
      const { error } = await supabase
        .from("invoices")
        .update({
          invoice_date: invoice.invoiceDate,
          client_id: invoice.clientId || null,
          request_id: invoice.requestId || null,
          estimate_id: invoice.estimateId || null,
          amount: invoice.amount,
          status: invoice.status,
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoices"] });
      toast.success("Счёт обновлён");
    },
    onError: () => toast.error("Ошибка при обновлении"),
  });
}

export function useDeleteInvoice() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("invoices").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["invoices"] });
      toast.success("Счёт удалён");
    },
    onError: () => toast.error("Ошибка при удалении"),
  });
}
