import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { Request } from "@/types/request";
import { toast } from "sonner";

export function useRequests() {
  return useQuery({
    queryKey: ["requests"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("requests")
        .select(`
          *,
          client:clients(id, company_name),
          object:service_objects(id, object_name),
          contract:documents(id, contract_number, response_conditions),
          responsible_manager:employees!requests_responsible_manager_id_fkey(id, full_name),
          assigned_team:teams(id, name),
          assigned_engineer:employees!requests_assigned_engineer_id_fkey(id, full_name)
        `)
        .order("created_at", { ascending: false });

      if (error) throw error;

      return data.map((row): Request => ({
        id: row.id,
        requestNumber: row.request_number,
        createdAt: new Date(row.created_at),
        status: row.status,
        type: row.type,
        priority: row.priority,
        clientId: row.client_id,
        clientName: row.client?.company_name || "",
        objectId: row.object_id,
        objectName: row.object?.object_name || "",
        contractId: row.contract_id || undefined,
        contractNumber: row.contract?.contract_number || undefined,
        contractConditions: row.contract?.response_conditions || row.contract_conditions || undefined,
        problemDescription: row.problem_description || "",
        comments: row.comments || "",
        desiredDate: row.desired_date || undefined,
        responsibleManagerId: row.responsible_manager_id || undefined,
        responsibleManagerName: row.responsible_manager?.full_name || undefined,
        assignedTeamId: row.assigned_team_id || undefined,
        assignedTeamName: row.assigned_team?.name || undefined,
        assignedEngineerId: row.assigned_engineer_id || undefined,
        assignedEngineerName: row.assigned_engineer?.full_name || undefined,
        plannedVisitDate: row.planned_visit_date || undefined,
        actualStartTime: row.actual_start_time || undefined,
        actualEndTime: row.actual_end_time || undefined,
        hoursSpent: row.hours_spent ? Number(row.hours_spent) : undefined,
      }));
    },
  });
}

export function useCreateRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (request: Partial<Request>) => {
      const { data, error } = await supabase
        .from("requests")
        .insert({
          request_number: "", // Will be auto-generated by trigger
          status: request.status || "new",
          type: request.type || "repair",
          priority: request.priority || "normal",
          client_id: request.clientId!,
          object_id: request.objectId!,
          contract_id: request.contractId || null,
          contract_conditions: request.contractConditions || null,
          problem_description: request.problemDescription || "",
          comments: request.comments || "",
          desired_date: request.desiredDate || null,
          responsible_manager_id: request.responsibleManagerId || null,
          assigned_team_id: request.assignedTeamId || null,
          assigned_engineer_id: request.assignedEngineerId || null,
          planned_visit_date: request.plannedVisitDate || null,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["requests"] });
      toast.success("Заявка создана");
    },
    onError: (error) => {
      console.error("Create request error:", error);
      toast.error("Ошибка при создании заявки");
    },
  });
}

export function useUpdateRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...request }: Partial<Request> & { id: string }) => {
      const { error } = await supabase
        .from("requests")
        .update({
          status: request.status,
          type: request.type,
          priority: request.priority,
          client_id: request.clientId,
          object_id: request.objectId,
          contract_id: request.contractId || null,
          contract_conditions: request.contractConditions || null,
          problem_description: request.problemDescription,
          comments: request.comments,
          desired_date: request.desiredDate || null,
          responsible_manager_id: request.responsibleManagerId || null,
          assigned_team_id: request.assignedTeamId || null,
          assigned_engineer_id: request.assignedEngineerId || null,
          planned_visit_date: request.plannedVisitDate || null,
          actual_start_time: request.actualStartTime || null,
          actual_end_time: request.actualEndTime || null,
          hours_spent: request.hoursSpent || null,
        })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["requests"] });
      toast.success("Заявка обновлена");
    },
    onError: () => toast.error("Ошибка при обновлении"),
  });
}

export function useDeleteRequest() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("requests").delete().eq("id", id);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["requests"] });
      toast.success("Заявка удалена");
    },
    onError: () => toast.error("Ошибка при удалении"),
  });
}
